export const actionTypes = {
  ADD_TASK_SUCCESS: 'ADD_TASK_SUCCESS',
  FAILURE: 'FAILURE',
  GET_TASKS_SUCCESS: 'GET_TASKS_SUCCESS',
  TOGGLE_DONE: 'TOGGLE_DONE',
  CLEAR_ALL_SUCCESS: 'CLEAR_ALL_SUCCESS',
}
