const stringTypes = {
  ADD_TASK_SUCCESS: "ADD_TASK_SUCCESS",
  FAILURE: "FAILURE",
  GET_TASKS_SUCCESS: "GET_TASKS_SUCCESS",
  CHANGE_FORM: "CHANGE_FORM",
  RESET_FORM: "RESET_FORM",
  TOGGLE_DONE: "TOGGLE_DONE",
  CLEAR_ALL_SUCCESS: "CLEAR_ALL_SUCCESS"
};

export default stringTypes;
