const types = {
  ADD_TASK_SUCCESS: "ADD_TASK_SUCCESS",
  ADD_TASKS_FAILURE: "ADD_TASKS_FAILURE",
  GET_TASKS_SUCCESS: "GET_TASKS_SUCCESS",
  GET_TASKS_FAILURE: "GET_TASKS_FAILURE",
  CHANGE_FORM: "CHANGE_FORM",
  RESET_FORM: "RESET_FORM",
  TOGGLE_DONE: "TOGGLE_DONE",
  CLEAR_ALL: "CLEAR_ALL",
};

export default types;
